"""0002

Revision ID: 181a22b3b799
Revises: 7b53216717de
Create Date: 2023-09-18 18:51:48.100511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '181a22b3b799'
down_revision: Union[str, None] = '7b53216717de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_name', table_name='products')
    op.create_unique_constraint(None, 'products', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.create_index('ix_products_name', 'products', ['name'], unique=False)
    # ### end Alembic commands ###
