"""0005

Revision ID: 4a4114edf33e
Revises: 6b2652e8b803
Create Date: 2023-09-18 19:24:36.205205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a4114edf33e'
down_revision: Union[str, None] = '6b2652e8b803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_info_links',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_info_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['product_info_id'], ['product_info.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'product_info_id')
    )
    op.add_column('product_prices', sa.Column('product_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'product_prices', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_prices', type_='foreignkey')
    op.drop_column('product_prices', 'product_id')
    op.drop_table('product_info_links')
    # ### end Alembic commands ###
