"""0004

Revision ID: 6b2652e8b803
Revises: b62beeb4fd33
Create Date: 2023-09-18 19:00:13.313790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b2652e8b803'
down_revision: Union[str, None] = 'b62beeb4fd33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'product_categories', ['product_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'product_category_id')
    # ### end Alembic commands ###
